// <auto-generated />
using System;
using BadDinosaurCodeTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BadDinosaurCodeTest.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240907113257_Scores")]
    partial class Scores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BadDinosaurCodeTest.Data.Entity.DinoClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Teacher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DinoClass");
                });

            modelBuilder.Entity("BadDinosaurCodeTest.Data.Entity.Dinosaur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dinosaurs");
                });

            modelBuilder.Entity("BadDinosaurCodeTest.Data.Entity.Scores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DinoClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DinosaurId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DinoClassId");

                    b.HasIndex("DinosaurId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("BadDinosaurCodeTest.Data.Entity.Scores", b =>
                {
                    b.HasOne("BadDinosaurCodeTest.Data.Entity.DinoClass", "DinoClass")
                        .WithMany()
                        .HasForeignKey("DinoClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadDinosaurCodeTest.Data.Entity.Dinosaur", "Dinosaur")
                        .WithMany()
                        .HasForeignKey("DinosaurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DinoClass");

                    b.Navigation("Dinosaur");
                });
#pragma warning restore 612, 618
        }
    }
}
